### ISSUE TITLE
Convert events into data

### ISSUE THREAD

**Issue by MatheusRich** [Ruby-DF/site#4]
Events can be described in a yaml file and the pages can be generated automatically. Possible structure:

```yml
title: "Ruby DF #1"
date: 2023-10-07 10:00:00 -0300
picture: /events/2023-10.jpg
talks:
  - title: Taming God Objects - Easy, incremental and safe
    author:
      name: Matheus Richard
      picture: /speakers/matheus.jpg # nullable
      link: https://twitter.com/matheusrich   
    slides: https://slides.com/123 # nullable
location: Universidade de Brasília - Faculdade do Gama
```
